/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-13 20:58:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Integer userId = (Integer) session.getAttribute("userId");
	String name = (String) session.getAttribute("name");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("  <title>Tendura</title>\r\n");
      out.write("  <link rel=\"icon\" href=\"images/tendura1.png\" type=\"image/png\" />\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"css/home.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"bg-light d-flex flex-column\">\r\n");
      out.write("  <nav class=\"navbar custom navbar-light bg-light fixed-top\" style=\"opacity: 90%;\">\r\n");
      out.write("    <div class=\"logo1\">\r\n");
      out.write("      <a href=\"Home.jsp\" class=\"navbar-brand\">\r\n");
      out.write("        <span class=\"fw-bold text-brown fs-1 text-s5\">Tendura</span>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"tabs\">\r\n");
      out.write("      <ul class=\"nav\" style=\"margin: 0%;\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active custom\" href=\"Home.jsp\">Home</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link custom\" href=\"#\">About Us</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link custom\" href=\"#\">Contact Us</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link custom\" href=\"#\">FAQs</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <div class=\"button-container\">\r\n");
      out.write("        <a href=\"Login.jsp\"><button class=\"btn custom2 btn-lg\" id=\"login\">Login</button></a>\r\n");
      out.write("        <a href=\"Register.jsp\"><button class=\"btn custom bg-brown btn-lg\" id=\"register\">Register</button></a>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("     <div class=\"dropdown profile\" id=\"profile\">\r\n");
      out.write("  <button class=\"btn dropdown-toggle btn-lg text-brown fw-6\" type=\"button\" id=\"dropdownMenuButton1\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("    Welcome, ");
      out.print(name );
      out.write("\r\n");
      out.write("  </button>\r\n");
      out.write("  <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton1\" style=\"min-width: 100%;\">\r\n");
      out.write("    <li>\r\n");
      out.write("      <a class=\"dropdown-item fs-5 text-brown\" href=\"userProfile.jsp\">\r\n");
      out.write("        <i class=\"bi bi-person-circle me-2 text-brown\"></i> Profile\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("      <a class=\"dropdown-item fs-5 text-brown\" href=\"logout\">\r\n");
      out.write("        <i class=\"bi bi-box-arrow-right me-2 text-brown\"></i> Logout\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <main>\r\n");
      out.write("    <div class=\"video-container\">\r\n");
      out.write("      <video src=\"videos/video1.mp4\" autoplay loop muted playsinline class=\"full-video\"></video>\r\n");
      out.write("      <div class=\"video-text\">\r\n");
      out.write("        \"Welcome to Tendura : Experience Comfort, Luxury, and Unforgettable Moments.\"\r\n");
      out.write("        <button class=\"btn btn-outline-light btn-xl\" style=\"margin-left: 70px;\">Book Now</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"content-container bg-light d-block\" >\r\n");
      out.write("\r\n");
      out.write("      <center>\r\n");
      out.write("        <div class=\"con\">\r\n");
      out.write("          <h1 class=\"fs-1\" style=\"padding-bottom: 20px;\">Tendura Hotel</h1>\r\n");
      out.write("          <p class=\"fs-4\">Experience unparalleled comfort and elegance at Tendura Hotel, where every stay is a blend of luxury and personalized service. Nestled in the heart of Sri Lanka, Tendura Hotel offers guests a serene retreat with modern amenities and warm hospitality.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"con\">\r\n");
      out.write("          <h2 class=\"mt-5 mb-1\">Standard Room : Comfort Meets Elegance</h2>\r\n");
      out.write("          <img src=\"images/pic1.jpg\" class=\"img-fluid mt-5 mb-5\">\r\n");
      out.write("          <p class=\"fs-4 \" style=\"text-align: justify;\">Our Standard Room at Tendura Hotel is the perfect blend of modern convenience and cozy elegance, designed for guests who value comfort, style, and affordability. Whether youâre traveling for business or leisure, this room offers a relaxing environment equipped with all the essentials for a memorable stay.\r\n");
      out.write("\r\n");
      out.write("            Step into a thoughtfully arranged space featuring a plush queen-sized bed dressed in premium linens, soft pillows, and ambient lighting that sets a restful tone. Large windows fill the room with natural light and provide a calming view of the surrounding cityscape or tranquil garden, depending on your selected room type.\r\n");
      out.write("            \r\n");
      out.write("            For your convenience, the Standard Room includes a work desk with ample lighting, complimentary high-speed Wi-Fi, a flat-screen TV with satellite channels, a mini-fridge, and a tea/coffee making station. A spacious wardrobe and a digital safe are also available to store your valuables securely.\r\n");
      out.write("            \r\n");
      out.write("            The en-suite bathroom is equipped with a walk-in shower, fresh towels, a hairdryer, and a selection of eco-friendly toiletries to ensure you have everything you need during your stay. Daily housekeeping keeps your space fresh and inviting throughout your visit.\r\n");
      out.write("            \r\n");
      out.write("            Guests staying in the Standard Room also enjoy access to our 24-hour room service, front desk support, and optional airport transfers upon request. With a strong focus on cleanliness, comfort, and customer service, our Standard Rooms provide exceptional value for solo travelers, couples, or even small families.\r\n");
      out.write("            \r\n");
      out.write("            Book your stay in our Standard Room and discover why Tendura Hotel is known for quality hospitality and peaceful rest, right in the heart of Sri Lanka.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"con\">\r\n");
      out.write("          <h2 class=\"mt-5 mb-1\">Suite Room : Luxury and Comfort Combined</h2>\r\n");
      out.write("          <img src=\"images/pic2.jpg\" class=\"img-fluid mt-5 mb-5\">\r\n");
      out.write("          <p class=\"fs-4 \" style=\"text-align: justify;\">At Tendura Hotel, our Suite Room redefines the art of luxury. Offering an expansive living space that combines style, comfort, and functionality, the Suite Room is the perfect choice for those seeking an elevated experience during their stay. Whether youâre visiting for business, a special occasion, or simply looking to indulge in ultimate comfort, our Suite Room caters to all your needs with a touch of sophistication.\r\n");
      out.write("\r\n");
      out.write("            As you step into the Suite, you are greeted by an elegant and spacious living area with carefully curated decor, modern furnishings, and a soothing color palette. The Suite features a separate bedroom with a lavish king-sized bed adorned with soft, high-quality linens, fluffy pillows, and ambient lighting, ensuring a restful sleep throughout your stay. The expansive windows offer panoramic views of the surrounding landscapes, providing a perfect backdrop for relaxation or intimate moments.\r\n");
      out.write("            \r\n");
      out.write("            The Suite Room also comes with a comfortable seating area, ideal for unwinding after a busy day or hosting a small gathering. Whether youâre enjoying a cup of coffee, reading, or working, the cozy seating nook creates a peaceful corner for every need.\r\n");
      out.write("            \r\n");
      out.write("            For your convenience and entertainment, the Suite includes a smart TV, high-speed Wi-Fi, a well-stocked mini-bar, and a tea/coffee making station. A spacious wardrobe and a digital safe ensure that your belongings are stored securely and within reach.\r\n");
      out.write("            \r\n");
      out.write("            The en-suite bathroom is a haven of relaxation, equipped with a luxurious soaking bathtub, a walk-in rain shower, and a double vanity. Youâll also find high-end toiletries, fresh towels, and a hairdryer, allowing you to enjoy the utmost comfort and cleanliness.\r\n");
      out.write("            \r\n");
      out.write("            Our Suite Room also offers personalized services, including 24-hour room service, dedicated concierge assistance, and priority access to hotel amenities. If you wish to experience the finest aspects of Tendura Hotel, our Suite provides exclusive privileges to ensure every aspect of your stay is perfect.\r\n");
      out.write("            \r\n");
      out.write("            Whether you're here for business, a romantic getaway, or just to unwind, the Suite Room at Tendura Hotel promises an unforgettable stay in a setting that is as luxurious as it is welcoming.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </center>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("  </main>\r\n");
      out.write("\r\n");
      out.write("  <footer class=\"bg-light text-brown text-center py-4 mt-5\">\r\n");
      out.write("    <center>\r\n");
      out.write("      <hr style=\"width: 98%; border: 2px #422100;\" class=\"mb-5\">\r\n");
      out.write("    </center>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <p class=\"mb-2\">© 2025 Tendura Hotel. All rights reserved.</p>\r\n");
      out.write("      <p class=\"mb-3\">\r\n");
      out.write("        <a href=\"#\" class=\"text-brown text-decoration-none\">Privacy Policy</a> | \r\n");
      out.write("        <a href=\"#\" class=\"text-brown text-decoration-none\">Terms of Service</a>\r\n");
      out.write("      </p>\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"#\" class=\"text-brown mx-2\">\r\n");
      out.write("          <i class=\"bi bi-facebook\"></i> Facebook\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"text-brown mx-2\">\r\n");
      out.write("          <i class=\"bi bi-twitter\"></i> Twitter\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"text-brown mx-2\">\r\n");
      out.write("          <i class=\"bi bi-instagram\"></i> Instagram\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("  		var checkId = 0;\r\n");
      out.write("\r\n");
      out.write("  		");
 if (userId != null && userId != 0) { 
      out.write("\r\n");
      out.write("   		 checkId = 1;\r\n");
      out.write("  		");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("  		if (checkId === 1) {\r\n");
      out.write("    		document.getElementById(\"profile\").style.display = \"block\"; \r\n");
      out.write("    		document.getElementById(\"login\").style.display = \"none\";\r\n");
      out.write("   		 	document.getElementById(\"register\").style.display = \"none\";\r\n");
      out.write("  		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
