/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-19 14:56:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Tendura - Login</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"images/tendura1.png\" type=\"image/png\" />\r\n");
      out.write("    <link href=\"css/login.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"bg-light d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar custom navbar-light bg-light fixed-top\" style=\"opacity: 90%;\">\r\n");
      out.write("        <div class=\"logo1\">\r\n");
      out.write("          <a href=\"Home.jsp\" class=\"navbar-brand\">\r\n");
      out.write("            <span class=\"fw-bold text-brown fs-1 text-s5\">Tendura</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tabs\">\r\n");
      out.write("          <ul class=\"nav\" style=\"margin: 0%;\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link custom\" href=\"Home.jsp\">Home</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link custom\" href=\"#\">About Us</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link custom\" href=\"#\">Contact Us</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link custom\" href=\"faqs.jsp\">FAQs</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("    <center>\r\n");
      out.write("      <hr style=\"width: 98%; border: 2px #422100;\" class=\"mb-5\">\r\n");
      out.write("    </center>\r\n");
      out.write("\r\n");
      out.write("    <form method=\"post\" action=\"log\" class=\"d-flex justify-content-center align-items-center vh-100\">\r\n");
      out.write("        <div class=\"container custom shadow bg-white rounded-3\">\r\n");
      out.write("            <h1 class=\"p-4 text-brown\">Login</h1>\r\n");
      out.write("            ");
 String error = (String) request.getAttribute("error"); 
      out.write("\r\n");
      out.write("			");
 if (error != null) { 
      out.write("\r\n");
      out.write("			  <p style=\"color:red;\">");
      out.print( error );
      out.write("</p>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <input class=\"input1 border rounded\" type=\"text\" name=\"username\" placeholder=\"Username\" ><br>\r\n");
      out.write("                <input class=\"input1 border rounded\" type=\"password\" name=\"password\" placeholder=\"********\" ><br>\r\n");
      out.write("                <button  class=\"m-5 btn-brown btn-lg\" type=\"submit\" name=\"submit\" >Login</button><br>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("            <p class=\"pb-5\">Don't have an account? <a href=\"Register.jsp\">Register</a></p>\r\n");
      out.write("           \r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      <footer class=\"bg-light text-brown text-center py-4 mt-5\">\r\n");
      out.write("    <center>\r\n");
      out.write("      <hr style=\"width: 98%; border: 2px #422100;\" class=\"mb-5\">\r\n");
      out.write("    </center>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <p class=\"mb-2\">© 2025 Tendura Hotel. All rights reserved.</p>\r\n");
      out.write("      <p class=\"mb-3\">\r\n");
      out.write("        <a href=\"#\" class=\"text-brown text-decoration-none\">Privacy Policy</a> | \r\n");
      out.write("        <a href=\"#\" class=\"text-brown text-decoration-none\">Terms of Service</a>\r\n");
      out.write("      </p>\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"#\" class=\"text-brown mx-2\">\r\n");
      out.write("          <i class=\"bi bi-facebook\"></i> Facebook\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"text-brown mx-2\">\r\n");
      out.write("          <i class=\"bi bi-twitter\"></i> Twitter\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"text-brown mx-2\">\r\n");
      out.write("          <i class=\"bi bi-instagram\"></i> Instagram\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
